apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: governance

resources:
  - ns.yaml
  - datahub-values.yaml

# DataHub provides Data Discovery, Lineage, and Data Governance.
# This namespace will also host SOC 2 compliance policy enforcement tools via OPA Gatekeeper.
